---

- name: install nginx
  apt:
    name: nginx
    state: present

#- name: configure nginx for log transport
#  template: src=nginx.conf dest=/etc/ningx.conf

- name: start nginx
  service: name=nginx state=started enabled=yes

- name: configure rsyslog for nginx access log transport
  template: src=01-nginx-access.conf.j2 dest=/etc/rsyslog.d/01-nginx-access.conf

- name: configure rsyslog for nginx error log transport
  template: src=02-nginx-error.conf.j2 dest=/etc/rsyslog.d/02-nginx-error.conf


- name: restart rsyslog
  service: name=rsyslog state=restarted