---

- hosts: all
  become: yes
  roles: 
  - common

- hosts: web
  become: yes
  roles:
  - nginx
  - web

- hosts: database
  become: yes
  roles:
  - db

- hosts: loadbalancer
  become: yes
  roles:
  - lb

#- hosts: monitoring
#  become: yes
#  roles:
#  - nginx
#  - monitoring

- hosts: logs
  become: yes
  roles:
  - nginx
  - logs

